In [15]:
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [16]:
dataset = pd.read_csv("roo_data.csv")

In [17]:
dataset.iloc[:,-1]

0                               Database Developer
1                             Portal Administrator
2                             Portal Administrator
3                   Systems Security Administrator
4                         Business Systems Analyst
                           ...                    
19995                           Technical Engineer
19996                           E-Commerce Analyst
19997                Business Intelligence Analyst
19998    Software Quality Assurance (QA) / Testing
19999                       Applications Developer
Name: Suggested Job Role, Length: 20000, dtype: object

In [18]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
l=12
len(data[0])

38

In [19]:
dataset.iloc[:,14:38]

can work long time before system? self-learning capability?  \
0                                   yes                       yes   
1                                   yes                        no   
2                                   yes                        no   
3                                    no                       yes   
4                                    no                        no   
...                                 ...                       ...   
19995                               yes                        no   
19996                               yes                        no   
19997                               yes                       yes   
19998                                no                        no   
19999                               yes                       yes   

      Extra-courses did        certifications          workshops  \
0                   yes     shell programming    cloud computing   
1                   yes      machine learning  database security   
2                   yes       app development   web technologies   
3                    no                python       data science   
4                    no       app development    cloud computing   
...                 ...                   ...                ...   
19995                no       app development    cloud computing   
19996                no            full stack   game development   
19997               yes  information security  database security   
19998                no            full stack    cloud computing   
19999               yes       app development  database security   

      talenttests taken? olympiads reading and writing skills  \
0                     no       yes                  excellent   
1                     no        no                       poor   
2                     no       yes                       poor   
3                    yes        no                     medium   
4                     no        no                       poor   
...                  ...       ...                        ...   
19995                yes        no                       poor   
19996                 no       yes                     medium   
19997                yes       yes                     medium   
19998                 no       yes                       poor   
19999                 no       yes                  excellent   

      memory capability score    Interested subjects  ... interested in games  \
0                   excellent        cloud computing  ...                  no   
1                      medium               networks  ...                 yes   
2                   excellent                hacking  ...                 yes   
3                   excellent               networks  ...                  no   
4                   excellent  Computer Architecture  ...                 yes   
...                       ...                    ...  ...                 ...   
19995               excellent   Software Engineering  ...                 yes   
19996               excellent             Management  ...                 yes   
19997               excellent               networks  ...                 yes   
19998                    poor                    IOT  ...                  no   
19999               excellent                    IOT  ...                  no   

      Interested Type of Books Salary Range Expected In a Realtionship?  \
0                 Prayer books                salary                 no   
1                    Childrens                salary                yes   
2                       Travel                  Work                 no   
3                      Romance                  Work                yes   
4                    Cookbooks                salary                 no   
...                        ...                   ...                ...   
19995                 Journals                  Work                yes   
19996 

In [20]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [21]:
labelencoder = LabelEncoder()

In [22]:
for i in range(14,38):
    data[:,i] = labelencoder.fit_transform(data[:,i])
data[:5]

array([[69, 63, 78, 87, 94, 94, 87, 84, 61, 9, 4, 0, 4, 8, 1, 1, 1, 8, 0,
        0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0, 0, 1, 0],
       [78, 62, 73, 60, 71, 70, 73, 84, 91, 12, 7, 1, 2, 3, 1, 0, 1, 5,
        2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0, 0, 1],
       [71, 86, 91, 87, 61, 81, 72, 72, 94, 11, 1, 4, 1, 3, 1, 0, 1, 0,
        7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1, 0, 0, 1],
       [76, 87, 60, 84, 89, 73, 62, 88, 69, 7, 1, 1, 2, 5, 0, 1, 0, 6, 1,
        1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1, 1, 1, 1],
       [92, 62, 90, 67, 71, 89, 73, 71, 73, 4, 5, 4, 6, 3, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0, 1, 1]],
      dtype=object)

In [23]:
dataset.iloc[:,:14]

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                      78                                  87   
1                                      73                                  60   
2                                      91                                  87   
3                                      60                                  84   
4                                      90                                  67   
...                                   ...                                 ...   
19995                                  62                                  63   
19996                                  83                                  87   
19997                                  80                                  87   
19998                                  91                                  88   
19999                                  74                                  84   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                                   94                                  94   
1                                   71                                  70   
2                                   61                                  81   
3                                   89                                  73   
4                                   71                                  89   
...                                ...                                 ...   
19995                               81                                  74   
19996                               82                                  66   
19997                               64                                  85   
19998                               66                                  74   
19999                               70                                  65   

       Percentage in Computer Architecture  Percentage in Mathematics  \
0                                       87                         84   
1                                       73                         84   
2                                       72                         72   
3                                       62                         88   
4                                       73                         71   
...                                    ...                        ...   
19995                                   90                         84   
19996                                   66                         92   
19997                                   69                         94   
19998                                   61                         87   
19999                                   92                         73   

       Percentage in Communication skills  Hours working per day  \
0                                      61                      9   
1                                      91                     12   
2                                      94                     11   
3                      

In [24]:
data[:5,14:]

array([[1, 1, 1, 8, 0, 0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0,
        0, 1, 0],
       [1, 0, 1, 5, 2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0,
        0, 1],
       [1, 0, 1, 0, 7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1,
        0, 0, 1],
       [0, 1, 0, 6, 1, 1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1,
        1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0,
        1, 1]], dtype=object)

In [25]:
from sklearn.preprocessing import Normalizer

In [26]:
data1=data[:,:14]

In [27]:
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)

(20000, 14)


In [28]:
normalized_data

array([[0.28508989, 0.26029947, 0.32227553, ..., 0.        , 0.01652695,
        0.0330539 ],
       [0.34997994, 0.27818918, 0.32754533, ..., 0.00448692, 0.00897384,
        0.01346077],
       [0.29501244, 0.35733901, 0.37811453, ..., 0.01662042, 0.0041551 ,
        0.01246531],
       ...,
       [0.3430836 , 0.28934762, 0.33068299, ..., 0.02480122, 0.00826707,
        0.01240061],
       [0.29479246, 0.37716094, 0.39450167, ..., 0.01734073, 0.03901665,
        0.02167592],
       [0.31140896, 0.32847247, 0.31567484, ..., 0.00426588, 0.02986113,
        0.02559526]])

In [29]:
data2=data[:,14:]
data2.shape

(20000, 24)

In [30]:
df1 = np.append(normalized_data,data2,axis=1)
df1.shape

(20000, 38)

In [31]:
## adding headers

X1 = pd.DataFrame(df1,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert'])

X1.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                  0.28509                 0.260299   
1                                  0.34998                 0.278189   
2                                 0.295012                 0.357339   
3                                 0.328025                 0.375503   
4                                 0.397157                 0.267649   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                           0.322276                           0.359461   
1                           0.327545                           0.269215   
2                           0.378115                           0.361494   
3                           0.258967                           0.362554   
4                           0.388523                           0.289234   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                        0.388383                           0.388383   
1                        0.318571                           0.314085   
2                        0.253461                           0.336563   
3                        0.384135                           0.315077   
4                        0.306502                           0.384206   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                            0.359461                  0.347066   
1                            0.327545                  0.376901   
2                            0.299168                  0.299168   
3                              0.2676                  0.379819   
4                            0.315136                  0.306502   

  Percentage in Communication skills Hours working per day  ...  \
0                           0.252036             0.0371856  ...   
1                            0.40831             0.0538431  ...   
2                            0.39058             0.0457062  ...   
3                           0.297812             0.0302129  ...   
4                           0.315136             0.0172677  ...   

  interested in games Interested Type of Books Salary Range Expected  \
0                   0                       21                     1   
1                   1                        5                     1   
2                   1                       29                     0   
3                   0                       23                     0   
4                   1                        7                     1   

  In a Realtionship? Gentle or Tuff behaviour? Management or Technical  \
0                  0                         1                       0   
1                  1                         0                       1   
2                  0                         1                       0   
3                  1                         0                       0   
4                  0                         1                       0   

  Salary/work hard/smart worker worked in teams ever? Introvert  
0           0                 0                     1         0  
1           0                 0                     0         1  
2           1                 0                     0         1  
3           1                 1                     1         1  
4           1                 0                     1         1  

[5 rows x 38 columns]

In [32]:
label1=dataset.iloc[:,-1]

In [33]:
label1

0                               Database Developer
1                             Portal Administrator
2                             Portal Administrator
3                   Systems Security Administrator
4                         Business Systems Analyst
                           ...                    
19995                           Technical Engineer
19996                           E-Commerce Analyst
19997                Business Intelligence Analyst
19998    Software Quality Assurance (QA) / Testing
19999                       Applications Developer
Name: Suggested Job Role, Length: 20000, dtype: object

In [34]:
arr=np.unique(label1)

In [35]:
Dict = {}
for i in range(0,34): 
    Dict[arr[i]] = i

In [36]:
Dict

{'Applications Developer': 0,
 'Business Intelligence Analyst': 1,
 'Business Systems Analyst': 2,
 'CRM Business Analyst': 3,
 'CRM Technical Developer': 4,
 'Data Architect': 5,
 'Database Administrator': 6,
 'Database Developer': 7,
 'Database Manager': 8,
 'Design & UX': 9,
 'E-Commerce Analyst': 10,
 'Information Security Analyst': 11,
 'Information Technology Auditor': 12,
 'Information Technology Manager': 13,
 'Mobile Applications Developer': 14,
 'Network Engineer': 15,
 'Network Security Administrator': 16,
 'Network Security Engineer': 17,
 'Portal Administrator': 18,
 'Programmer Analyst': 19,
 'Project Manager': 20,
 'Quality Assurance Associate': 21,
 'Software Developer': 22,
 'Software Engineer': 23,
 'Software Quality Assurance (QA) / Testing': 24,
 'Software Systems Engineer': 25,
 'Solutions Architect': 26,
 'Systems Analyst': 27,
 'Systems Security Administrator': 28,
 'Technical Engineer': 29,
 'Technical Services/Help Desk/Tech Support': 30,
 'Technical Support': 

In [37]:
label = labelencoder.fit_transform(label)
print(len(label))

20000


In [38]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])
y.head()

Suggested Job Role
0                   7
1                  18
2                  18
3                  28
4                   2

# Decision Tree Classifier

In [39]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=10) 

In [40]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [42]:
y_pred = clf.predict(X_test)

In [43]:
y_pred

array([29,  6,  5, ..., 23, 17, 15])

In [44]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [45]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*1000)

confusion matrics= [[ 1  9  2 ...  6  3  1]
 [ 2  4  3 ...  4  1  5]
 [ 1  4  0 ...  4  5  4]
 ...
 [ 4  2  4 ...  3  1  6]
 [ 4  3  1 ... 10  5  3]
 [ 2  6  0 ...  2  2  3]]
  
accuracy= 30.25


# With entropy

In [46]:
clf_entropy = tree.DecisionTreeClassifier(criterion = "entropy", random_state = 10)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=10, splitter='best')

In [47]:
entropy_y_pred=clf_entropy.predict(X_test)

In [48]:
cm_entopy = confusion_matrix(y_test,entropy_y_pred)

In [49]:
entropy_accuracy = accuracy_score(y_test,entropy_y_pred)

In [50]:
print("confusion matrics=",cm_entopy)
print("  ")
print("accuracy=",l*entropy_accuracy*100)

confusion matrics= [[1 3 7 ... 3 2 2]
 [2 4 3 ... 3 2 4]
 [1 2 4 ... 0 3 1]
 ...
 [1 6 3 ... 0 5 2]
 [3 2 4 ... 2 2 4]
 [5 1 6 ... 6 6 4]]
  
accuracy= 32.4


# Support Vector Machines

In [51]:
from sklearn import svm

In [52]:
clf = svm.SVC()
clf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [53]:
svm_y_pred = clf.predict(X_test)

In [54]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [55]:
print("confusion matrics=",svm_cm)
print("  ")
print("accuracy=",l*svm_accuracy*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 67.2


# XGBoost

In [56]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=10) 

In [57]:
X_train.shape

(14000, 38)

In [58]:
X_train=pd.to_numeric(X_train.values.flatten())

In [59]:
X_train=X_train.reshape((14000,38))

In [60]:
from xgboost import XGBClassifier

In [61]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [62]:
xgb_y_pred = clf.predict(X_test)

In [63]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)

In [64]:
print("confusion matrics=",xgb_cm)
print("  ")
print("accuracy=",l*xgb_accuracy*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 69.0


# CHATBOT

In [65]:
import io
import random
import string
import warnings
import numpy as np
import pandas as pd

In [66]:
from sklearn import decomposition
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
'''
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download()
'''

In [68]:
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('popular', quiet=True)
f=open('chatbot.txt','r',errors = 'ignore')
RawData=f.read()
RawData = RawData.lower()

In [69]:
sent_tokens = nltk.sent_tokenize(RawData)# converts to list of sentences 
word_tokens = nltk.word_tokenize(RawData)# converts to list of words

In [70]:
lemmer = nltk.stem.WordNetLemmatizer()
#WordNet is a semantically-oriented dictionary of English included in NLTK.
def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)

def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [71]:
GREETING_INPUTS = ("hello", "hi", "greetings", "sup", "what's up","hey",)
GREETING_RESPONSES = ["Oy' mate! can i help you out today?", "Hello buddy! can i help you out today?", "*nods*", "Saheli at your service", "hello friend. can i help you out today?", "i am glad that you are talking to me"]

def greeting(sentence):
 
    for word in sentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)

In [72]:
#Various Responses out of which a random one will be picked
QUESTIONAIRE_Qs = ("What is your percentage in Operating Systems?" , "What about in Data Structures and Algorithms?" , "What about in Programming Concepts?" , "What about in in Software Engineering?", "What is your percentage in Computer Networks?", "What is your percentage in Electronics subjects?" , "What is your percentage in Computer Architecture?" , "What is your percentage in Mathematics?" , "What is your percentage in Communication skills?" , "How many hours working per day?" , "Rate your Logical quotient out of 10!" , " Number of hackathons attended?" ,"Rate your Coding skills out of 10." , " Rate your Public speaking skills as well out of 10" , " Do you think you're capable of working for long time before the system?" , " Can you learn things on your own and be a self-taught?" , " Strange question, you into extracurriculars?" , " What interests you more, Machine Learning or app development?" , "Choose one: Cloud computing, database security, game development, hacking, testing, data science!" , " Did you take any talent tests?" , " Did you attend any olympiads?" , "What best describes your Reading and writing skills: Excellent, medium or poor" , "What best describes your memory skills: Excellent, medium or poor" , "Name the most interesting subject you are interested in CS" , "Do you see yourself as a developer or a Business process analyst?" , "Would you prefer job or higherstudies?","What type of company do you want to work in?", "Have you taken any inputs from any seniors?", "Are you interested in games?","What kind of books are you into? because that matters too! :P", "Would you prefer work or salary?", "Do you have other commitments like clubs and departments?", "What do you think best describes you best: gentle or stubborn?", "Which one of the following are you more inclined towards: Management or technical?", "Would you prefer work or salary?", "Are you a hard worker or a smart worker?", "We're almost done here! I need to know whether you like working in teams?", "Last question, are you a shy person, an introvert?")
GREAT_WORK = ("That's amazing! ","Bravo, ","Nice, ","Good good.. ","Wohoo! ","I think I'm talking to an expert, ","I'm proud of you already haha! ", "wow! ", "Damn! Nice dude! ", "Hey that's pretty awesome if you ask me! ","Noice! ","Lovely! ","Nerd alert! ",)
MEDIUM_WORK = ("hey not bad! ","Umm, okay..","Ahem! ","Ahaan, ","Ohh ","Okay alright! ", "Shouldn't be that big a problem! ", "Oh acha, okay! ", "That's where most of us lie, right? haha! ")
POOR_WORK = ("Don't worry! ","Tbh, I didn't enjoy that subject either ","Yiiikes, ","Oh no, ","It's tough, yep! ","It's alright, ", "Ouch!! ", "OOPS! ", "Somebody wasn't paying attention, huh? ", "Oh no..", "That's bad dude! ", "It's okay, you can work on that! ",)
FINAL_ANSWER = ("That's the end of this quiz! After a lot of thinking, I think you should become a ", "We've come to the end of the quiz! My research suggests that you should become a ", "In my opinion, you should actually consider becoming a ", " My Final say is, You're best suited for the role of a ", "You must be wondering what I found out! You should definitely be a ", "That's the end of this quiz! After extenive research of your personal choices and academic backgroun, you should definitely be a ")

In [73]:
flag = True
 
relative_response = " "

in_quiz = False
collect_answer = False
percentage_question = True
question_no = -1;

ANSWERS = []

print("SAHELI: Hey")
while(flag==True):
    user_response = input()
    user_response=user_response.lower()
    
    if(user_response!='bye'):
        if(user_response=='thanks' or user_response=='thank you' ):
            flag=False
            print("SAHELI: You are welcome..")
        else:
            if(greeting(user_response)!=None):
                print("SAHELI: "+ "My name is Saheli. I aim to help you out with career guidance. If you want to exit, type Bye!" + greeting(user_response) + "! I believe you're confused about your ideal job role. If you want to take a quick questionnaire, type 'start'")

        if(user_response=='start'):
            in_quiz = True
            print("SAHELI: Great, Let's begin the quiz then")
            
        if(user_response.isdigit()):
            if(percentage_question):
                if(int(user_response) < 35):
                    relative_response = random.choice(POOR_WORK)
                if((int(user_response) < 65) & (int(user_response) > 35)):
                    relative_response = random.choice(MEDIUM_WORK)
                if(int(user_response) > 65):
                    relative_response = random.choice(GREAT_WORK)
            else:
                if(int(user_response) > 6):
                    relative_response = random.choice(GREAT_WORK)
                if((int(user_response) < 6) & (int(user_response) > 4)):
                    relative_response = random.choice(MEDIUM_WORK)
                if(int(user_response) < 4):
                    relative_response = random.choice(POOR_WORK)
        if(in_quiz):
            ####store the given answer in an array"
            ######################################
            ANSWERS.append(user_response)
            
            question_no = question_no + 1
            if(question_no == 38):
                in_quiz = False
                ###Call model with stored value"
                ###############################
                ###############################
                print("Saheli: WELL DONE!! Now please wait for me to think about your most optimal career path!")
                ANSWERS.remove('start')
                for i in range(14,38):
                    ANSWERS[14:38] = labelencoder.fit_transform(ANSWERS[14:38])
                for i in range(0,14):
                    ANSWERS[i]= int(ANSWERS[i])
                ANSWERS_ARRAY = np.asarray(ANSWERS)
                data123=data
                ANS=ANSWERS_ARRAY
                ANS.reshape(1,38)
                ANS1=np.reshape(ANS,(1,38))
                new_data = np.append(data123,ANS1,axis=0)
                new_data_for_normalization = new_data[:,:14]
                normalized_data_for_prediction = Normalizer().fit_transform(new_data_for_normalization)
                print(normalized_data_for_prediction.shape)
                remaining_data = new_data[:,14:]
                new_df = np.append(normalized_data_for_prediction,remaining_data,axis=1)
                prediction_array = new_df[20000,:]
                prediction_array.reshape(1,-1)
                prediction_array2d= [prediction_array]
                clf = svm.SVC()
                clf.fit(X_train, y_train)
                predicted_value = clf.predict(prediction_array2d)
                
                
                print(random.choice(FINAL_ANSWER) + list(Dict.keys())[list(Dict.values()).index(predicted_value[0])] )
                data123=data
                ANS=ANSWERS_ARRAY
                #predict the output of the model using ANSWERS
                
                print("Saheli: Thank you for taking this quiz, please say 'bye' to exit")
                
                
            if(question_no > 8):
                percentage_question = False
            print("SAHELI: " + relative_response + QUESTIONAIRE_Qs[question_no])

            collect_answer = True
            relative_response = ""
            
    else:
        flag=False
        print("SAHELI: Bye! take care..")
        
  
        

SAHELI: Hey
Hi
SAHELI: My name is Saheli. I aim to help you out with career guidance. If you want to exit, type Bye!*nods*! I believe you're confused about your ideal job role. If you want to take a quick questionnaire, type 'start'
start
SAHELI: Great, Let's begin the quiz then
SAHELI:  What is your percentage in Operating Systems?
40
SAHELI: Oh acha, okay! What about in Data Structures and Algorithms?
20
SAHELI: Ouch!! What about in Programming Concepts?
60
SAHELI: That's where most of us lie, right? haha! What about in in Software Engineering?
30
SAHELI: Oh no, What is your percentage in Computer Networks?
10
SAHELI: Oh no, What is your percentage in Electronics subjects?
20
SAHELI: Tbh, I didn't enjoy that subject either What is your percentage in Computer Architecture?
20
SAHELI: Ouch!! What is your percentage in Mathematics?
90
SAHELI: Bravo, What is your percentage in Communication skills?
49
SAHELI: That's where most of us lie, right? haha! How many hours working per day?
12
SA

IndexError: tuple index out of range